version: '3.8'

services:
  # Backend service (Convex functions)
  taskflow-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend service (React app)
  taskflow-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - taskflow-backend
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.separated.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - taskflow-frontend
    restart: unless-stopped
