// This file will be generated by the backend
// For now, we'll use a placeholder that points to your backend API
export const api = {
  auth: {
    loggedInUser: "auth.loggedInUser"
  },
  tasks: {
    getUserTasks: "tasks.getUserTasks",
    createTask: "tasks.createTask",
    updateTask: "tasks.updateTask",
    deleteTask: "tasks.deleteTask",
    getTaskStats: "tasks.getTaskStats"
  },
  projects: {
    getUserProjects: "projects.getUserProjects",
    createProject: "projects.createProject",
    updateProject: "projects.updateProject",
    deleteProject: "projects.deleteProject"
  },
  comments: {
    getTaskComments: "comments.getTaskComments",
    addComment: "comments.addComment",
    deleteComment: "comments.deleteComment"
  }
};
